@startuml
class Item{
-description: String
-dueDate: Date
-completeStatus: boolean
+editDescription()
+editDueDate()
+markComplete()
+getDescription()
+getDueDate()
+getCompleteStatus()
}

class ToDoList{
-listTitle: String
-items: ArrayList
+editTitle()
+addItem()
+removeItem()
+getListTitle()
+getItems()
}

class Lists{
-toDoLists: Map
+addList()
+removeList()
+getLists()
}

class FileManager{
+saveOneList()
+saveAll()
+openOneList()
+openAll()
}

class ListDisplay{
+displayAllItems()
+displayUncompleted()
+displayCompleted()
}

class FXController{
+uaAddList()
+uaRemoveList()
+uaEditTitle()
+uaAddItem()
+uaRemoveItem()
+uaEditItem()
+uaMarkComplete()
+setItemView()
+uaSaveList()
+uaSaveAll()
+uaImportList()
+uaImportAll()
}

class App{
main()
start()
}

class InputValidator{
+checkFileName()
+checkDate()
}



App *-- FXController
FXController o-- Lists
FXController o-- ListDisplay
FXController o-- FileManager
FXController o-- InputValidator
Lists *-- ToDoList
ToDoList *-- Item
@enduml