@startuml
class Item{
-description: String
-dueDate: Date
-completeStatus: boolean
}

class ToDoList{
-listTitle: String
-items: ArrayList
+addItem()
+editItem()
+removeItem()
+markComplete()
+getListTitle()
+getItems()
}

class Lists{
-listMap: Map
+addList()
+removeList()
+getLists()
+mergeLists()
}

class FileManager{
+saveOneList()
+saveAll()
+openOneList()
+openAll()
}

class ListDisplay{
-displayArray: ArrayList
+displayItems()
-displayUncompleted()
-displayCompleted()
+emptyDisplayArray()
+getDisplayArray()
}

class ToDoController{
+mCheckUncompleted: CheckMenuItem
+mCheckCompleted: CheckMenuItem
+listView: ListView
+cbLists: ChoiceBox
+updateListView()
+updateCBList()
+mLoadListClicked()
+mLoadMultipleClicked()
+mSaveListClicked()
+mSaveAllListsClicked()
+mAddListClicked()
+mEditListClicked()
+mDeleteListClicked()
+mDisplayUncompletedClicked()
+mDisplayCompletedClicked()
+bAddItemClicked()
+bEditItemClicked()
+bDeleteItemClicked()
+bCompleteItemClicked()
}

class App{
main()
start()
}

class InputValidator{
+checkDate()
}




App -- ToDoController
ToDoController o-- Lists
ToDoController o-- ListDisplay
ToDoController o-- FileManager
ToDoController o-- InputValidator
Lists *-- ToDoList
ToDoList *-- Item
@enduml