@startuml
class Item{
-description: String
-dueDate: Date
-completeStatus: boolean
+editDescription()
+editDueDate()
+markComplete()
+getDescription()
+getDueDate()
+getCompleteStatus()
}

class ToDoList{
-listTitle: String
-items: ArrayList
+editTitle()
+addItem()
+removeItem()
+getListTitle()
+getItems()
}

class Lists{
-toDoLists: Map
+addList()
+removeList()
+getLists()
}

class FileManager{
+saveOneList()
+saveAll()
+openOneList()
+openAll()
}

class ListDisplay{
-displayArray: ArrayList
+displayItems()
-displayUncompleted()
-displayCompleted()
-emptyDisplayArray()
}

class ToDoController{

}

class App{
main()
start()
}

class InputValidator{
+checkDate()
}




App -- ToDoController
ToDoController o-- Lists
ToDoController o-- ListDisplay
ToDoController o-- FileManager
ToDoController o-- InputValidator
Lists *-- ToDoList
ToDoList *-- Item
@enduml